TECH Bug while receiving non text/json response content-type
transcovo/pymarsys pull request #12
Opened 2017-07-27 15:00 UTC by PerrinStephane

Parse json is need be

2017-07-28 07:42 UTC, Perados approved these changes
I wanted to fix this long time ago! Most of the messages caused by this were warnings, not errors, I think. :trollface:

2017-07-28 15:07 UTC, Perados requested changes
:trollface:

2017-07-28 15:07 UTC, Perados commented on pymarsys/connections.py
> +            if response.headers['Content-Type'] is 'text/json':
Use `==` to compare strings, not `is`. `is` compares the `id` of the object, not the real value. Strings are optimised in Python, so your string will probably have the same `id` in this situation, but still, `==` would be safer here IMO.

https://stackoverflow.com/questions/2988017/string-comparison-in-python-is-vs

2017-07-31 14:23 UTC, Tehem approved these changes
LGTM

2017-07-31 14:36 UTC, merged